### ISSUE TITLE
Include more intermittent failure bugs to be automatically closed

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1992]
```[tasklist]
### Tasks
- [ ] Drop the component filtering
- [ ] Include P3 bugs
- [ ] Include bugs that are not blocking other open bugs
- [ ] Drop the filtering for "blocked"
```
